MODEL:
  META_ARCHITECTURE: "student_ttda_mem_RCNN"
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    NUM_CLASSES: 1
  RESNETS:
    NORM: "FrozenBN" # Options: FrozenBN, GN, "SyncBN", "BN"
    OUT_FEATURES: ["res4"]
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATASETS:
  TRAIN: ("cityscape_car_2007_train_s",)
  TEST: ("cityscape_car_2007_test_s",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 0
TEST_TIME:
  TYPE: True
OUTPUT_DIR: "checkpoint/online_da_sim"